version: '3.8'

services:
  postgres:
    image: postgres
    container_name: mypostgresDBContainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Strongpassword1234
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/
